AllCops:
  TargetRubyVersion: 2.5

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/Debugger:
  Enabled: false

Metrics/AbcSize:
  Max: 70

Metrics/BlockLength:
  Max: 55

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 25

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - id
    - m
    - _m

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false
  # buggy when the difference is sleep / side-effects
