AllCops:
  TargetRubyVersion: 2.5

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/Debugger:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - id
    - m
    - _m
    - tz

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/DateTime:
  Enabled: false
  # If I can't achieve the same thing with Time, what's
  # the point of telling me not to use DateTime???

Style/Documentation:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false
  # buggy when the difference is sleep / side-effects
